### ISSUE TITLE
What does AVG_STABLE_NM in VCF output stand for?

### ISSUE THREAD

**Issue by CorinnaErnst** [kensung-lab/INSurVeyor#18]
I would like to know what the values of `AVG_STABLE_NM` refer to. The VCF header says `Description="Average NM of stable reads."`

But what is `NM`?  ... sorry if I missed it in the documentation or publication.

Many thanks in advance!

**Comment by Mesh89** [comment]
Hi, NM is a tag provided by BWA. It is the edit distance of the alignment:
https://bio-bwa.sourceforge.net/bwa.shtml (last table). 

The edit distance between two sequences is basically the minimum number of operations (insertions, deletions and substitutions, 1 character = 1 operation) in order to transform one string into the other.

In this case, it should be the number of bps inserted + the number of bps deleted + the number of mismatches.

**Comment by CorinnaErnst** [comment]
Many thanks!

**Comment by CorinnaErnst** [comment]
Many thanks!
